### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by hatzel** [hatzel/vorleser-server#4]
## Current
- [x] Access control
- [x] Recover from deletion
- [x] Set up suffcient amount of integartion tests for library scanning

## Future
- [x] Config file
- [x] Sqlite
- [ ] Re-encoding support
- [ ] Packaging
- [ ] sort out logging

## Far Future
- [ ] Collections of books
